### ISSUE TITLE
图片的存放方式

### ISSUE THREAD

**Issue by GhostFlying** [hz-ingress/ingress-tutorial#1]
图片存放如何解决？

放在github上的某个文件夹 or issue or 其它平台？

我之前是用的七牛。

**Comment by Jamesits** [comment]
在每个文件夹下面建一个 img 文件夹如何？GitBook 导出其他文件格式的时候如果图片在别的平台可能会出问题……

2015-04-21 0:11 GMT+08:00 GhostFlying notifications@github.com:

**Comment by GhostFlying** [comment]
但这样似乎就要单独用个commit来上传图片才能拿到链接？

**Comment by Jamesits** [comment]
不用的，直接用 path/to/image 引用该文件就好了

**Comment by GhostFlying** [comment]
好，我看了下 git scm 好像也是这么干的，那就这样好了

**Comment by Jamesits** [comment]
https://github.com/Jamesits/auto-image-cutter/blob/master/README.md
我这里有引用过图片，供参考。

似乎有个大坑是相对路径和绝对路径……

**Comment by GhostFlying** [comment]
这个感觉还好。。这方面最坑的还是图片尺寸的问题吧。。都要自己调整好，如果要点击缩放要准备两张图。。

**Comment by Jamesits** [comment]
先按原尺寸放一张试试，反正 GitBook 支持本地实时预览

**Comment by GhostFlying** [comment]
不行，要么准备两张，要么就要用纯 html，我之前都是直接用得 img 标签。。

**Comment by Jamesits** [comment]
现在体育课，我回寝室看一下

**Comment by Jamesits** [comment]
Solved with #4.

**Comment by Jamesits** [comment]
直接用全分辨率图片即可。
