### ISSUE TITLE
4.8.8中的描述错误

### ISSUE THREAD

**Issue by Nidhoggur1993** [hz-ingress/ingress-tutorial#11]
“COMM 查看和发送消息”这一功能，在半封号时不起作用，仅在intel map可使用comm
”Drop 道具“也是仅限于提示成功，但实际功能不奏效

**Comment by Jamesits** [comment]
其实现在提示成功这个事情很坑爹，网络不好的话可能任何操作都提示成功但是不加 AP，实际上没成功……
