### ISSUE TITLE
把所有图片替换成高分辨率版本

### ISSUE THREAD

**Issue by Jamesits** [hz-ingress/ingress-tutorial#5]
改了下 CSS，图片最大宽度会被限制在 300px。

并且请删除到图片源文件的链接，fancy box 会自动处理。

注意：图片的 Alt Text 会被 fancy box 作为标题显示出来。

**Comment by GhostFlying** [comment]
300 px 下，summary 图片显示的字看不清楚，不过增大了那些单独的图片又显得太宽。。

**Comment by Jamesits** [comment]
但是你可以戳图片看大图。

**Comment by GhostFlying** [comment]
我替换了一部分，那些 common， rare 和 vr 的路一排放不下，略蛋疼

看大图不是不可以，但是觉得原来能直接看清楚的图片。

我先改好，看下效果再说。

**Comment by Jamesits** [comment]
排不下就改成 200px 好了 = = CSS 文件在 _assets/website.css 

感觉应该这样：最顶上只放实物图片（不同掉率的三张），别的公式啊什么的以文字形式出现。

**Comment by Jamesits** [comment]
或者直接限制 max-height？感觉所有看上去太宽的图片其实都是太高了

**Comment by GhostFlying** [comment]
max-height = 300  感觉效果还行
