### ISSUE TITLE
想一起写gitbook，有需要帮忙的地方吗？

### ISSUE THREAD

**Issue by cafe3310** [hz-ingress/ingress-tutorial#9]

**Comment by Jamesits** [comment]
已邀请，在 SUMMERY.md 找到想要写的条目然后动手即可，格式参照已有条目。新手引导部分翻译自 Google 的帮助，主要需要写的是后面部分。

谢了。

**Comment by cafe3310** [comment]
OK /
顺便想加一节**新人问题FAQ**，最近冒出一大波新人，总是同样的问题解答起来很麻烦
我整理下聊天记录加上好了

**Comment by Jamesits** [comment]
加一节 FAQ 好了

**Comment by GhostFlying** [comment]
欢迎：） 这东西工作量看起来还是蛮大的。

**Comment by Jamesits** [comment]
鉴于最近新人多，我目前的计划是先把翻译官方说明的部分，以及新加的 FAQ 搞定，各位怎么看？

**Comment by cafe3310** [comment]
FAQ正在整理咯（ ~~虽说感觉聊天记录里的舰娘FAQ都比Ingress多~~

2015-04-28 17:50 GMT+08:00 James Swineson notifications@github.com:

> 鉴于最近新人多，我目前的计划是先把翻译官方说明的部分，以及新加的 FAQ 搞定，各位怎么看？
> 
> On Tue, Apr 28, 2015, 17:46 GhostFlying notifications@github.com wrote:
> 
> > 欢迎：） 这东西工作量看起来还是蛮大的。
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/hz-ingress/ingress-tutorial/issues/9#issuecomment-96991959>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hz-ingress/ingress-tutorial/issues/9#issuecomment-96992937
> .

## 

Sipan Junnan

tgmgsp@gmail.com

tgmerge.me

**Comment by Jamesits** [comment]
看出来了😂

**Comment by GhostFlying** [comment]
好，开始写哪部分在 issue 里说明下或者开个 branch push 下？不然容易重复

**Comment by Jamesits** [comment]
你在开始写之前先新建文件，写个标题并加入 not_finished_yet.md 模板，在 summary 添加对应链接，push 一次就好了。

**Comment by Jamesits** [comment]
Author added at 22797865dd88bae55adead0641bbe4e3d1bea0b5
